feeltiming/urls.py
from django.contrib import admin
from django.urls import path, include
#밑에 두개 임포트 했습니다. 23.06.24
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.main, name='main'),
    path('post', views.placepost, name='PlacePost'),
    path('data', views.create_data, name='CreateData'), 
]

user/urls.py
from django.urls import path
import user.views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', user.views.signup, name='signup'),
    path('mypage/<int:pk>/', user.views.mypage, name='mypage'),
]

main/models.py
from django.db import models

# Create your models here.
class smoking_area(models.Model):
    region= models.CharField(max_length=100, null=True)
    address= models.CharField(max_length=200, null=True)
    location= models.CharField(max_length=100, null=True)
    management= models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.location
    
class PlacePost(models.Model) : 
    PlaceAddress = models.CharField(max_length=100)
    PlaceName = models.CharField(max_length=50)
    PlaceExplain = models.TextField()
    PlacePhoto = models.ImageField(upload_to='request/')

    def __str__(self):
        return self.PlaceAddress

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    nickname = models.CharField(max_length=10)
    email = models.EmailField(max_length=50, unique=True)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models import User


class UserForm(UserCreationForm):
    nickname = forms.CharField(max_length=10)
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "nickname")

main/views.py
from django.shortcuts import render, redirect
from .models import *
import csv
def main(request):
    zone = smoking_area.objects.all()
    context = {'zone' : zone}
    return render(request, 'main/main.html', context)

def placepost(request):
    Place = PlacePost()
    Place.PlaceAddress = request.POST['PlaceAddress']
    Place.PlaceName = request.POST['PlaceName']
    Place.PlaceExplain = request.POST['PlaceExplain']
    Place.PlacePhoto = request.POST['PlacePhoto']
    Place.save()
    return redirect('/')

def create_data(request):
    CSV_PATH = 'C:/Users/User/Desktop/FeelTiming/static/main/data/total_data.csv'
    with open(CSV_PATH, newline='') as csvfile:
        print("afdadfsfsdfsd")
        data_reader = csv.DictReader(csvfile)
        for row in data_reader:
            smoking_area.objects.create(
                                region            = row['자치구'],
                                address           = row['설치주소'],
                                location          = row['설치위치'],
                                management        = row['운영관리'],
                        )
    return redirect('/')

user/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.

# 회원 가입
def signup(request):
    # signup 으로 POST 요청이 왔을 때, 새로운 유저를 만드는 절차를 밟는다.
    if request.method == 'POST':
        # password와 confirm에 입력된 값이 같다면
        if request.POST['password'] == request.POST['confirm']:
            # user 객체를 새로 생성
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            # 로그인 한다
            auth.login(request, user)
            return redirect('/')
    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'signup.html')

# 로그인
def login(request):
    # login으로 POST 요청이 들어왔을 때, 로그인 절차를 밟는다.
    if request.method == 'POST':
        # login.html에서 넘어온 username과 password를 각 변수에 저장한다.
        username = request.POST['username']
        password = request.POST['password']

        # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=username, password=password)
        
        # 해당 user 객체가 존재한다면
        if user is not None:
            # 로그인 한다
            auth.login(request, user)
            return redirect('/')
        # 존재하지 않는다면
        else:
            # 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            return render(request, 'login.html', {'error' : 'username or password is incorrect.'})
    # login으로 GET 요청이 들어왔을때, 로그인 화면을 띄워준다.
    else:
        return render(request, 'login.html')

# 로그 아웃
def logout(request):
    # logout으로 POST 요청이 들어왔을 때, 로그아웃 절차를 밟는다.
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/')

    # logout으로 GET 요청이 들어왔을 때, 로그인 화면을 띄워준다.
    return render(request, 'login.html')

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import UserForm
from django.contrib.auth import authenticate, login, get_user_model
# Create your views here.

# 회원 가입
def signup(request):
    # signup 으로 POST 요청이 왔을 때, 새로운 유저를 만드는 절차를 밟는다.
    if request.method == 'POST':
        form = UserForm(request.POST)
        # password와 confirm에 입력된 값이 같다면
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/')
    else:
        form = UserForm()
    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'user/signup.html', {'form': form})

def mypage(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {'user': user}
    return render(request, 'user/mypage.html', context)

templates/base.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Feel Timing</title>
		<!-- 부트스트랩 load -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
			crossorigin="anonymous"
		/>
		<script
			defer
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
			crossorigin="anonymous"
		></script>
		<!-- 부트스트랩 load 끝 -->
		<link href="{% static 'main/css/main.css' %}?after" rel="stylesheet" />
	</head>
	<body>
		<!-- 부트스트랩 navbar -->
		<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #9DD6FF">
			<div class="container-fluid">
				<div class="flex-shrink-0">
					<a class="navbar-brand" href="/">
						<img id="logo" src="/static/main/image/logo.png" alt="logo" />
					</a>
				</div>
				<h3
					class="navbar-text position-absolute top-50 start-50 translate-middle navbar-title"
					style="font-size: 150%"
				>
					흡연구역 지도
				</h3>
				{% if user.is_active %}
				<a class="navbar-brand" href="{% url 'user:mypage' user.id %}" style="right: 5%"> 마이페이지</a>
				{% else %}
				<a class="navbar-brand" href="/user/login" style="right: 5%">
					<img src="/static/main/image/Group.png" alt="info_icon" width="32" />
				</a>
				{% endif %}
			</div>
		</nav>
		{% block content %} {% comment %} 상속한 템플릿에서 구현해야 하는 영역 {% endcomment %} {% endblock %}
	</body>
</html>

templates/main/main.html
{% extends 'base.html' %} {% block content%}
<script
	type="text/javascript"
	src="//dapi.kakao.com/v2/maps/sdk.js?appkey=874e5437aaa21a99b99c21ed87291281&libraries=services"
></script>
<script src="/static/main/js/map.js" type="text/javascript"></script>
<!-- 부트스트랩 navbar -->
<div class="main">
	<!-- 지도 그리는 부분 -->
	<div calss="map_wrap">
		<div id="map">
			<!-- 지도타입 컨트롤 div 입니다 -->
			<div class="custom_typecontrol">
				<span id="roadviewbtn" onclick="getLoadView()">
					<img src="/static/main/image/road_view.svg" width="36" />
				</span>
				<span id="currentbtn" onclick="setCenter()">
					<img src="/static/main/image/setCurrent.png" width="36" />
				</span>
				<span id="enrollbtn" onclick="enroll()">
					<img src="/static/main/image/enroll.png" width="100" />
				</span>
				<script>
					var arr = [];
					{% for item in zone %}
					var loc = '{{ item.address }}'
					var desc = '{{ item.location }}';

					arr.push({'location' : loc, 'desc' : desc})
					{% endfor %}
					findGeo(arr);
				</script>
			</div>
			<div id="roadview"></div>
		</div>
	</div>
	<!-- 지도 그리기 끝 -->
	<div id="bottom_menu" style="background-color: #d9efff">
		<div>
			<a onclick="developed()"><img src="/static/main/image/community.png" /></a>
		</div>
		<div>
			<a href="/"><img src="/static/main/image/map.png" /></a>
		</div>
		<div>
			<a onclick="developed()"><img src="/static/main/image/mypage.png" /></a>
			<script>
				function developed() {
					alert("개발중");
				}
			</script>
		</div>
	</div>
	<!-- 끝 -->
	<div id="bottomBar" class="bottom_bar">
		<div class="buttons">
			<div class="address_box">
				<h1 id="address-1">#</h1>
				<br />
				<p id="address-2">#</p>
			</div>
			<div class="findRoute">
				<a id="link_route" href="#">
					<img src="/static/main/image/findRoute.png" width="60" />
				</a>
			</div>
			<div class="bottom_roadview">
				<a id="link_roadView" href="#">
					<img src="/static/main/image/roadView.png" width="120" />
				</a>
			</div>
			<div class="report">
				<img src="/static/main/image/report.png" width="120" />
			</div>
		</div>
	</div>
	<!-- 바텀 바 끝 -->
	<!-- 흡연 구역 등록 -->
	<div id="enroll_page">
		<div class="main-request">
			<!--요청 기본 안내부분-->
			<div class="request-guide">
				<span class="first_span">
					흡연구역으로 등록되어 있지 않은 곳 중,<br />
					흡연하기 적절한 장소로 판단되는 곳을 등록해주세요. <br />
				</span>
				<h6 class="grey" style="font-size: 90%; margin-top: 10px">적절한 흡연 구역의 조건 <br /></h6>
				<span>
					<ol class="grey">
						<li>1. 사람들이 많이 지나다니지 않는 곳(간접흡연 예방)</li>
						<li>2. 주변에 재떨이, 쓰레기통 등 꽁초를 버릴만한 통이 있는 곳</li>
					</ol>
				</span>
			</div>
			<!--요청 기본 안내부분 끝-->
			<!--등록 방법 안내-->
			<div class="howtorequest">
				<h2 class="title" style="text-align: center">등록 방법</h2>
				<span>
					<ol class="grey">
						<li>1. 지도에서 위치를 클릭하여 마커를 생성합니다.</li>
						<br />
						<li>2. 주소를 확인한 후, <해당위치로 흡연구역 등록> 버튼을 클릭합니다.</li>
						<br />
						<li>3. 추가 정보를 입력하고 등록을 완료합니다.</li>
					</ol>
				</span>
			</div>
			<!--등록 방법 안내 끝-->
			<!--제출 폼 시작 폼 안에 액션 채워야함!-->

			<form action="{%url 'PlacePost' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<ul>
					<li class="subtitle">
						<label for="address">주소</label>
						<!--이부분 주소 채워야합니다-->
						<br />
						<input id="enroll-address" name="PlaceAddress" class="content" value=" " />
					</li>
					<li class="subtitle">
						<label for="PlaceName">장소 이름</label>
						<br />
						<input type="text" name="PlaceName" id="PlaceName" value=" " />
					</li>
					<li class="subtitle">
						장소 설명 <br />
						<textarea name="PlaceExplain" id="PlaceExplain" cols="30" rows="10"></textarea>
					</li>
					<li class="subtitle">
						<label for="PlacePhoto">장소 사진</label>
						<br />
						<input class="photo" type="file" name="PlacePhoto" />
					</li>
				</ul>
				<button class="submit" type="submit" onclick="abc()"></button>
				<script>
					function abc() {
						alert(
							"흡연구역 등록 신청이 완료되었습니다.\n신청하신 흡연구역은 필타이밍이 검토 후\n흡연구역으로 등록해드립니다.\n\n흡연자들의 흡연문화 개선을 위해 꾸준히 노력하겠습니다. 감사합니다."
						);
					}
				</script>
			</form>
		</div>
	</div>
	<!-- 흡연 구역 끝 -->
	{% endblock %}
</div>

templates/request/request.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Feel Timing Recommend</title>
  </head>
  <body>
    <!--요청창 전체-->
    <div class="main-request">
      <!--요청 기본 안내부분-->
      <div class="request-guide">
        <span>
          흡연구역으로 등록되어 있지 않은 곳 중,<br />
          흡연하기 적절한 장소로 판단되는 곳을 등록해주세요.<br />
        </span>

        <span> 적절한 흡연 구역의 조건 <br /> </span>
        <span>
          <ol>
            <li>사람들이 많이 지나다니지 않는 곳(간접흡연 예방)</li>
            <li>주변에 재떨이, 쓰레기통 등 꽁초를 버릴만한 통이 있는 곳</li>
          </ol>
        </span>
      </div>
      <!--요청 기본 안내부분 끝-->
      <!--등록 방법 안내-->
      <div class="howtorequest">
        <span>등록 방법</span>
        <span>
          <ol>
            <li>지도에서 위치를 클릭하여 마커를 생성합니다.</li>
            <br />
            <li>
              주소를 확인한 후, <해당위치로 흡연구역 등록> 버튼을 클릭합니다.
            </li>
            <br />
            <li>추가 정보를 입력하고 등록을 완료합니다.</li>
          </ol>
        </span>
      </div>
      <!--등록 방법 안내 끝-->
      <!--제출 폼 시작 폼 안에 액션 채워야함!-->
      <form
        action="{%url 'PlacePost' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {%csrf_token%}
        <ul>
          <li>
            <label for="address">주소</label
            ><!--이부분 주소 채워야합니다-->
          </li>
          <li>
            <label for="PlaceName">장소 이름</label>
            <input type="text" name="PlaceName" id="PlaceName" value=" " />
          </li>
          <li>
            장소 설명 <br />
            <textarea
              name="PlaceExplain"
              id="PlaceExplain"
              cols="30"
              rows="10"
            ></textarea>
          </li>
          <li>
            <label for="PlacePhoto">장소 사진</label>
            <input type="file" name="PlacePhoto" />
          </li>
        </ul>
        <input type="submit" value="제출하기" />
      </form>
    </div>
  </body>
</html>

templates/user/login.html
{% extends 'base.html' %} {% block content%}
<div class="container">
	<div class="row">
		<div class="col-sm-5">
			<h2>로그인</h2>
			<br />
			<form class="row g-3" method="post" action="{% url 'user:login' %}">
				{% csrf_token %}
				<div class="col-md-7">
					<label for="username">사용자ID</label>
					<input
						type="text"
						class="form-control"
						name="username"
						id="username"
						value="{{ form.username.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-md-7">
					<label for="password">비밀번호</label>
					<input
						type="password"
						class="form-control"
						name="password"
						id="password"
						value="{{ form.password.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-12">
					<button type="submit" class="btn btn-primary">로그인</button>
				</div>
			</form>
			<br />
			<div class="mb-3">
				<a href="#" onclick="developed()" style="text-decoration: none">아이디 찾기</a>
			</div>
			<div class="mb-3">
				<a href="#" onclick="developed()" style="text-decoration: none">비밀번호 재설정</a>
			</div>
			<div class="mb-3">
				<a href="/user/signup" style="text-decoration: none">회원가입</a>
			</div>
			<script>
				function developed() {
					alert("개발중");
				}
			</script>
		</div>
	</div>
</div>

{% endblock %}

templates/user/main.html
{% if user.is_authenticated %}
    <p>{{ user.username }}</p>
    <a href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
    <form id="logout" method="POST" action="{% url 'logout' %}">
        {% csrf_token %} <input type="hidden" />
    </form>
{% else %}
    <a href="{% url 'signup' %}">회원가입</a>
    <a href="{% url 'login' %}">로그인</a>
{% endif %}

templates/user/mypage.html
{% extends 'base.html' %} {% block content%}
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			{% if user.is_authenticated %}
			<div class="row g-3">
				<div class="col-md-9">
					<label class="highlight">아이디</label><br />
					<label class="form-label">{{ user.username }}</label>
				</div>
				<br />
				<div class="col-md-9">
					<label class="highlight">닉네임</label><br />
					<label class="form-label">{{ user.nickname }}</label>
				</div>
				<div class="col-md-9">
					<label class="highlight">이메일</label><br />
					<label class="form-label">{{ user.email }}</label>
				</div>
				<a href="/">홈으로</a>
			</div>
		</div>
		{% else %} 회원이 아닙니다.
		<br />
		<a href="/">홈으로</a>
		{% endif %}
	</div>
</div>
{% endblock %}

templates/user/signup.html
{% extends 'base.html' %} {% block content%}
<div class="container" style="">
	<h2>회원가입</h2>
	<br />
	<div class="row">
		<div class="col-sm-4">
			<form method="post" action="{% url 'user:signup' %}" class="row g-3">
				{% csrf_token %}
				<div class="col-md-7">
					<label for="username">아이디</label>
					<input
						type="text"
						name="username"
						id="username"
						value="{{ form.username.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-md-7">
					<label for="nickname">닉네임</label>
					<input
						type="text"
						name="nickname"
						id="nickname"
						value="{{ form.nickname.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-md-7">
					<label for="password1">비밀번호</label><br />
					( 영문 + 숫자 8자 이상 )
					<input
						type="password"
						name="password1"
						id="password1"
						value="{{ form.password1.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-md-7">
					<label for="password2">비밀번호 확인</label>
					<input
						type="password"
						name="password2"
						id="password2"
						value="{{ form.password2.value|default_if_none:'' }}"
					/>
				</div>
				<div class="col-md-7">
					<label for="email">이메일</label>
					<input type="text" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" />
				</div>
				<div class="col-md-7">
					<label for="region">주소</label>
					<input type="text" name="region" id="region" value="{{ form.region.value|default_if_none:'' }}" />
				</div>
				<div class="col-12">
					<button type="submit" class="btn btn-primary">회원가입</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}